
name: Build Executables

on:
  push:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, x86, armv8, armv7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install .
        pip install pyinstaller
    - name: Modify file with sed
      run: sed -i 's/from . import main/from payload_dumper import main/' src/payload_dumper/__main__.py
    - name: Build with PyInstaller
      run: pyinstaller --onefile --name payload_dumper-${{runner.os}}  src/payload_dumper/__main__.py
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: payload_dumper
        path: dist/
